chore: remove old Travis CI badge and update .npmignore
eslint-community/eslint-plugin-promise pull request #242
Opened 2021-12-18 20:05 UTC by nschonni

**What is the purpose of this pull request?**

- [ ] Documentation update
- [ ] Bug fix
- [ ] New rule
- [ ] Changes an existing rule
- [ ] Add autofixing to a rule
- [x] Other, please explain:

**What changes did you make? (Give an overview)**
Update build badge now that GitHub Actions is used. When removing the old reference to .travis.yml, saw that there were some other dotfiles that weren't ignored right now

2022-09-28 23:35 UTC, ota-meshi approved these changes

2022-09-29 00:45 UTC, MichaelDeBoey requested changes

2022-09-29 00:45 UTC, MichaelDeBoey commented on README.md
> +[![CI](https://github.com/xjamundx/eslint-plugin-promise/actions/workflows/CI.yml/badge.svg)](https://github.com/xjamundx/eslint-plugin-promise/actions/workflows/CI.yml)
```suggestion
[![CI](https://github.com/eslint-community/eslint-plugin-promise/actions/workflows/CI.yml/badge.svg)](https://github.com/eslint-community/eslint-plugin-promise/actions/workflows/CI.yml)
```

2022-09-29 00:46 UTC, MichaelDeBoey approved these changes

2022-09-29 00:46 UTC, merged